<div class="footer_links_wrapper accordion" id="accordion" data-mage-init='{"accordion_custom": {"breakpoint":"768", "headerClass": "accordion_links_header"}}'>
    <div data-role="collapsible" class="footer_links_block">
            <h2 data-role="trigger" class="accordion_links_header accordion_closed"><?= __('Links list 1')?></h2>
        <ul data-role="content" class="footer_links_list">
            <li class="footer_links_items nav item">
                <a href="#" class="footer_link link"><?= __('Link 1')?></a>
            </li>
            <li class="footer_links_items nav item">
                <a href="#" class="footer_link link"><?= __('Link 2')?></a>
            </li>
            <li class="footer_links_items nav item">
                <a href="#" class="footer_link link"><?= __('Link 3')?></a>
            </li>
            <li class="footer_links_items nav item">
                <a href="#" class="footer_link link"><?= __('Link 4')?></a>
            </li>
        </ul>
    </div>
    <div data-role="collapsible" class="footer_links_block">
            <h2 data-role="trigger" class="accordion_links_header accordion_closed"><?= __('Links list 2')?></h2>
        <ul data-role="content" class="footer_links_list">
            <li class="footer_links_items nav item">
                <a href="#" class="footer_link link"><?= __('Link 1')?></a>
            </li>
            <li class="footer_links_items nav item">
                <a href="#" class="footer_link link"><?= __('Link 2')?></a>
            </li>
            <li class="footer_links_items nav item">
                <a href="#" class="footer_link link"><?= __('Link 3')?></a>
            </li>
            <li class="footer_links_items nav item">
                <a href="#" class="footer_link link"><?= __('Link 4')?></a>
            </li>
        </ul>
    </div>
    <div data-role="collapsible" class="footer_links_block">
            <h2 data-role="trigger" class="accordion_links_header accordion_closed"><?= __('Links list 3')?></h2>
        <ul data-role="content" class="footer_links_list">
            <li class="footer_links_items nav item">
                <a href="#" class="footer_link link"><?= __('Link 1')?></a>
            </li>
            <li class="footer_links_items nav item">
                <a href="#" class="footer_link link"><?= __('Link 2')?></a>
            </li>
            <li class="footer_links_items nav item">
                <a href="#" class="footer_link link"><?= __('Link 3')?></a>
            </li>
            <li class="footer_links_items nav item">
                <a href="#" class="footer_link link"><?= __('Link 4')?></a>
            </li>
        </ul>
    </div>
</div>
<div class="footer_social_wrapper">
    <div class="footer_social_links">
        <h2 class="footer_social_links_header"><?= __('Follow us on')?></h2>
        <ul class="footer_social_list">
            <li class="footer_social_item">
                <a href="" class="footer_social_link">
                    <i class="fab fa-twitter-square fa-3x"></i>
                </a>
            </li>
            <li class="footer_social_item">
                <a href="" class="footer_social_link">
                    <i class="fab fa-facebook-square fa-3x"></i>
                </a>
            </li>
            <li class="footer_social_item">
                <a href="" class="footer_social_link">
                    <i class="fab fa-pinterest-square fa-3x"></i>
                </a>
            </li>
            <li class="footer_social_item">
                <a href="" class="footer_social_link">
                    <i class="fab fa-youtube-square fa-3x"></i>
                </a>
            </li>
            <li class="footer_social_item">
                <a href="" class="footer_social_link">
                    <i class="fab fa-instagram fa-3x"></i>
                </a>
            </li>
        </ul>
    </div>
</div>
