<div class="main_content_wrapper">
    <aside class="aside">
        <nav class="aside_nav">
            <ul class="aside_nav_list">
                <li class="aside_nav_list_item">
                    <a href="#" class="aside_nav_list_link"><?= __('Link')?></a>
                </li>
                <li class="aside_nav_list_item">
                    <a href="#" class="aside_nav_list_link"><?= __('Link')?></a>
                </li>
                <li class="aside_nav_list_item">
                    <a href="#" class="aside_nav_list_link"><?= __('Link')?></a>
                </li>
                <li class="aside_nav_list_item">
                    <a href="#" class="aside_nav_list_link"><?= __('Link')?></a>
                </li>
                <li class="aside_nav_list_item">
                    <a href="#" class="aside_nav_list_link"><?= __('Link')?></a>
                </li>
                <li class="aside_nav_list_item">
                    <a href="#" class="aside_nav_list_link"><?= __('Link')?></a>
                </li>
                <li class="aside_nav_list_item">
                    <a href="#" class="aside_nav_list_link"><?= __('Link')?></a>
                </li>
                <li class="aside_nav_list_item">
                    <a href="#" class="aside_nav_list_link"><?= __('Link')?></a>
                </li>
            </ul>
        </nav>
    </aside>
    <section class="main_section">
        <div class="section_paragraph_container">
            <h2 class="section_paragraph_container_header">
                <?= __('ipsum dolor sit amet, consectetur adipisicing elit.')?>
            </h2>
            <p class="section_paragraph_container_text">
                Lorem ipsum dolor sit amet, consectetur adipisicing elit.
                A amet cumque dicta distinctio dolor doloremque est excepturi fugiat harum impedit inventore
                iusto molestias nam nesciunt placeat quibusdam quidem tempora, veritatis!
                Accusamus ad blanditiis distinctio facilis ipsa nemo, nostrum possimus tenetur voluptatum.
                At doloremque illum similique sit voluptas! Aliquid at dicta dolorem fugit officiis repellat ut
                vero. Ea quod sapiente tenetur!
            </p>
        </div>
        <div class="section_paragraph_container">
            <h3 class="section_paragraph_container_header">
                <?= __('ipsum dolor sit amet, consectetur adipisicing elit.')?>
            </h3>
            <p class="section_paragraph_container_text">
                Lorem ipsum dolor sit amet, consectetur adipisicing elit.
                A amet cumque dicta distinctio dolor doloremque est excepturi fugiat harum impedit inventore
                iusto molestias nam nesciunt placeat quibusdam quidem tempora, veritatis!
                Accusamus ad blanditiis distinctio facilis ipsa nemo, nostrum possimus tenetur voluptatum.
                At doloremque illum similique sit voluptas! Aliquid at dicta dolorem fugit officiis repellat ut
                vero. Ea quod <a class="section_paragraph_container_text_link" href="#">sapiente</a>
                <a class="section_paragraph_container_text_link" href="#">tenetur</a>!
            </p>
        </div>
        <div class="section_paragraph_container">
            <h3 class="section_paragraph_container_header">
                <?= __('ipsum dolor sit amet, consectetur adipisicing elit.')?>
            </h3>
            <p class="section_paragraph_container_text">
                Lorem ipsum dolor sit amet, consectetur adipisicing elit.
                A amet cumque dicta distinctio dolor doloremque est excepturi fugiat harum impedit inventore
                iusto molestias nam nesciunt placeat quibusdam quidem tempora, veritatis!
                Accusamus ad blanditiis distinctio facilis ipsa nemo, nostrum possimus tenetur voluptatum.
                At doloremque illum similique sit voluptas! Aliquid at dicta dolorem fugit officiis repellat ut
                vero. Ea quod sapiente tenetur!
            </p>
        </div>
        <div class="section_paragraph_container">
            <h3 class="section_paragraph_container_header">
                <?= __('ipsum dolor sit amet, consectetur adipisicing elit.')?>
            </h3>
            <p class="section_paragraph_container_text">
                Lorem ipsum dolor sit amet, consectetur adipisicing elit.
                A amet cumque dicta distinctio dolor doloremque est excepturi fugiat harum impedit inventore
                iusto molestias nam nesciunt placeat quibusdam quidem tempora, veritatis!
                Accusamus ad blanditiis distinctio facilis ipsa nemo, nostrum possimus tenetur voluptatum.
                At doloremque illum similique sit voluptas! Aliquid at dicta dolorem fugit officiis repellat ut
                vero. Ea quod sapiente tenetur!
            </p>
        </div>
        <div class="section_paragraph_container">
            <h3 class="section_paragraph_container_header">
                <?= __('ipsum dolor sit amet, consectetur adipisicing elit.')?>
            </h3>
            <ul class="section_paragraph_container_list">
                <li class="section_paragraph_container_list_item">
                    <?= __('Lorem ipsum dolor sit amet, consectetur')?>
                </li>
                <li class="section_paragraph_container_list_item">
                    <?= __('Lorem ipsum dolor sit amet, consectetur')?>
                </li>
                <li class="section_paragraph_container_list_item">
                    <?= __('Lorem ipsum dolor sit amet, consectetur')?>
                </li>
                <li class="section_paragraph_container_list_item">
                    <?= __('Lorem ipsum dolor sit amet, consectetur')?>
                </li>
                <li class="section_paragraph_container_list_item">
                    <?= __('Lorem ipsum dolor sit amet, consectetur')?>
                </li>
                <li class="section_paragraph_container_list_item">
                    <?= __('Lorem ipsum dolor sit amet, consectetur')?>
                </li>
            </ul>
        </div>
    </section>
</div>