<div class="footer_copyright_wrapper">
    <div class="footer_copyright_text">
        © 2018 Southern Carlson. All Rights Reserved. Use of this site is subject to certain
        <a href="#" class="footer_copyright_link"><?= __('Terms To Use')?></a>
    </div>
    <div class="footer_copyright_links">
        <a href="#" class="footer_copyright_link"><?= __('Privacy Policy')?></a>
        <a href="#" class="footer_copyright_link"><?= __('Sitemap')?></a>
        <a href="#" class="footer_copyright_link"><?= __('Terms of Sale')?></a>
    </div>
</div>
