<div class="footer_info_wrapper">
    <div class="footer_info_logo">
        <a href="#" class="footer_info_logo_link">
            <img src="<?php echo $this->getViewFileUrl('images/logo.png'); ?>" alt="" class="footer_info_logo_image">
        </a>
    </div>

    <div class="footer_info_socials_links">
        <a href="#" class="footer_info_socials_link">
            <img src="<?php echo $this->getViewFileUrl('images/facebook.png'); ?>" alt="" class="footer_info_socials_image">
        </a>
        <a href="#" class="footer_info_socials_link">
            <img src="<?php echo $this->getViewFileUrl('images/twitter.png'); ?>" alt="" class="footer_info_socials_image">
        </a>
        <a href="#" class="footer_info_socials_link">
            <img src="<?php echo $this->getViewFileUrl('images/pinterest.png'); ?>" alt="" class="footer_info_socials_image">
        </a>
        <a href="#" class="footer_info_socials_link">
            <img src="<?php echo $this->getViewFileUrl('images/insta.png'); ?>" alt="" class="footer_info_socials_image">
        </a>
    </div>

    <div class="footer_info_special_block">
        <h3 class="footer_info_special_header">Special Financing Available Everyday</h3>
        <div class="footer_info_special_links">
            <a href="#" class="footer_info_special_link">Pay & Manage Your Card</a>
            <a href="#" class="footer_info_special_link">Credit Offers</a>
        </div>
    </div>
</div>