<?php

/** @var \Magento\Framework\View\Element\Template\ $block */

?>

<div class="block block-customer-login">
<script type="text/-x-magento-init">
    {
        "*":{
            "Magento_Ui/js/core/app": {
                "components": {
                    "logged": {
                        "component": "Magento_Theme/js/logged"
                    }
                }
            }
        }
    }
</script>

</div>



