<div data-block="dropdown" class="header_menu_wrapper">
    <div data-trigger="trigger" class="header_menu_trigger">
        <span class="header_menu_icon"></span>
        <span class="header_menu_text">Shop Products</span>
    </div>

    <div class="block nav_wrapper"
         data-mage-init='{"header_menu": {}}'>
        <nav class="menu_navigation" data-mage-init='{"mage/tabs": {"collapsibleElement": "[data-role=collap]", "head": "[data-role=title]", "content": "[data-role=cont]",
            "trigger": "[data-role=trig]","openedState": "active", "animate": {"duration": 100}, "active": 0, "disabledState": "enable"}}'>
            <div class="menu_tabs_wrapper">
                <div class="menu_tabs_item" data-role="collap">
                    <a class="menu_tabs_link" data-toggle="trig" href="#tab-shop"><?= __('Shop')?>Shop</a>
                </div>
                <div class="menu_tabs_item" data-role="collap">
                    <a class="menu_tabs_link" data-toggle="trig" href="#tab-acc"><?= __('Account')?>Account</a>
                </div>
            </div>
            <ul id="tab-shop" data-role="cont" class="menu_navigation_list">
                <li class="menu_navigation_item">
                    <a href="#" class="menu_navigation_link"><?= __('Anchors')?></a>
                </li>
                <li class="menu_navigation_item">
                    <a href="#" class="menu_navigation_link"><?= __('Apparel & Accessories')?></a>
                </li>
                <li class="menu_navigation_item">
                    <a href="#" class="menu_navigation_link"><?= __('Bolts Nuts & Washers')?></a>
                </li>
                <li class="menu_navigation_item">
                    <a href="#" class="menu_navigation_link"><?= __('Building Materials')?></a>
                </li>
                <li class="menu_navigation_item">
                    <a href="#" class="menu_navigation_link"><?= __('Job Site Supplies')?></a>
                </li>
                <li class="menu_navigation_item">
                    <a href="#" class="menu_navigation_link"><?= __('Maintenance')?></a>
                </li>
                <li data-role="collapsible" class="menu_navigation_item menu_before">
                    <a data-role="trigger" href="#" class="menu_navigation_link link_closed"><?= __('Nails')?></a>
                    <ul data-role="content" class="menu_navigation_list__drop">
                        <li class="menu_navigation_item level_2">
                            <a href="#" class="menu_navigation_link link_closed"><?= __('Bulk/Hand-Drive')?></a>
                        </li>
                        <li data-role="collapsible" class="menu_navigation_item level_2">
                            <a href="#" data-role="trigger" class="menu_navigation_link link_closed"><?= __('Collated')?></a>
                            <ul data-role="content" class="menu_navigation_list__drop_last">
                                <li class="menu_navigation_item level_3">
                                    <a href="#" class="menu_navigation_link"><?= __('All Collated')?></a>
                                </li>
                                <li class="menu_navigation_item level_3">
                                    <a href="#" class="menu_navigation_link"><?= __('Brads')?></a>
                                </li>
                                <li class="menu_navigation_item level_3">
                                    <a href="#" class="menu_navigation_link"><?= __('Cleats')?></a>
                                </li>
                                <li class="menu_navigation_item level_3">
                                    <a href="#" class="menu_navigation_link"><?= __('Finish Nails')?></a>
                                </li>
                            </ul>
                        </li>
                    </ul>
                </li>
                <li class="menu_navigation_item">
                    <a href="#" class="menu_navigation_link"><?= __('Packaging')?></a>
                </li>
                <li class="menu_navigation_item">
                    <a href="#" class="menu_navigation_link"><?= __('Power Tools')?></a>
                </li>
            </ul>

            <ul id="tab-acc" data-role="cont" class="menu_navigation_list">
                <li class="menu_navigation_item">
                    <a href="#" class="menu_navigation_link"><?= __('My account')?></a>
                </li>
                <li class="menu_navigation_item">
                    <a href="#" class="menu_navigation_link"><?= __('Create account')?></a>
                </li>
            </ul>
        </nav>
    </div>
</div>
