<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var $block \Magento\Catalog\Block\Product\View */
?>

<?php $_product = $block->getProduct(); ?>
<?php $buttonTitle = __('Add to Cart'); ?>
<?php if ($_product->isSaleable()) : ?>
    <div class="box-tocart">
        <div class="fieldset">
            <?php if ($block->shouldRenderQuantity()) : ?>
                <div class="field qty" data-mage-init='{"Magento_Catalog/js/quantity":{}}'>
                    <div class="control">
                        <input type="button"
                               name="decrement"
                               id="decr"
                               value="<?= $block->escapeHtmlAttr(__('-')) ?>"
                               title="<?= $block->escapeHtmlAttr(__('-')) ?>"
                               class="input-decrement"
                        />
                    </div>
                    <label class="label" for="qty"><span><?= $block->escapeHtml(__('Quantity')) ?></span></label>
                    <div class="control">
                        <input type="number"
                               name="qty"
                               id="qty"
                               min="0"
                               value="<?= $block->getProductDefaultQty() * 1 ?>"
                               title="<?= $block->escapeHtmlAttr(__('Qty')) ?>"
                               class="input-text qty"
                               data-validate="<?= $block->escapeHtmlAttr(json_encode($block->getQuantityValidators())) ?>"
                        />
                    </div>
                    <div class="control">
                        <input type="button"
                               name="increment"
                               id="incr"
                               value="<?= $block->escapeHtmlAttr(__('+')) ?>"
                               title="<?= $block->escapeHtmlAttr(__('+')) ?>"
                               class="input-increment"
                        />
                    </div>
                </div>
            <?php endif; ?>
            <div class="actions">
                <button type="submit"
                        title="<?= $block->escapeHtmlAttr($buttonTitle) ?>"
                        class="action primary tocart"
                        id="product-addtocart-button" disabled>
                    <span><?= $block->escapeHtml($buttonTitle) ?></span>
                </button>
                <?= $block->getChildHtml('', true) ?>
            </div>
        </div>
    </div>
<?php endif; ?>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Magento_Catalog/js/validate-product": {}
        }
    }
</script>
