<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Catalog\Block\Product\View\Details $block */
?>
<?php if ($detailedInfoGroup = $block->getGroupSortedChildNames('detailed_info', 'getChildHtml')) :?>
    <div class="product info detailed">
        <div class="content_links_bar_wrapper" data-mage-init='{"Magento_Catalog/js/stickybar":{}}'>
            <ul class="content_links_bar_list">
                <li class="content_links_bar_item">
                    <a href="#description" class="content_links_bar_link"><?= __('Description')?></a>
                </li>
                <li class="content_links_bar_item">
                    <a href="#specifications" class="content_links_bar_link"><?= __('Specifications')?></a>
                </li>
                <li class="content_links_bar_item">
                    <a href="#recommended" class="content_links_bar_link"><?= __('Recommended')?></a>
                </li>
                <li class="content_links_bar_item">
                    <a href="#downloads" class="content_links_bar_link"><?= __('Downloads')?></a>
                </li>
            </ul>
            <span class="content_links_bar_scroll">
            <a href="#" class="content_links_bar_scroll_link"<?= __('Back to Top')?>></a>
    </span>
        </div>
        <?php $layout = $block->getLayout(); ?>
        <div class="product data items">
            <?php foreach ($detailedInfoGroup as $name) :?>
                <?php
                $html = $layout->renderElement($name);
                if (!trim($html)) {
                    continue;
                }
                $alias = $layout->getElementAlias($name);
                $label = $block->getChildData($alias, 'title');
                ?>
                <div class="data item content"
                     aria-labelledby="tab-label-<?= $block->escapeHtmlAttr($alias) ?>-title" id="<?= $block->escapeHtmlAttr($alias) ?>">
                    <?= /* @noEscape */ $html ?>
                </div>
            <?php endforeach;?>
        </div>
    </div>
<?php endif; ?>



