<div class="categories_section">
    <h1 class="categories_section_header">Featured Categories</h1>
    <div class="categories_section_block">
        <img src="<?php echo $this->getViewFileUrl('images/bulk.png'); ?>" alt="Bulk Nails" class="categories_section_block_image">
        <div class="categories_section_block_item">Bulk Nails</div>
    </div>
    <div class="categories_section_block">
        <img src="<?php echo $this->getViewFileUrl('images/collated.png'); ?>" alt="Collated Nails" class="categories_section_block_image">
        <div class="categories_section_block_item">Collated Nails</div>
    </div>
    <div class="categories_section_block">
        <img src="<?php echo $this->getViewFileUrl('images/staplers.png'); ?>" alt="Staplers" class="categories_section_block_image">
        <div class="categories_section_block_item">Staplers</div>
    </div>
    <div class="categories_section_block">
        <img src="<?php echo $this->getViewFileUrl('images/shrink.png'); ?>" alt="Shrink Film" class="categories_section_block_image">
        <div class="categories_section_block_item">Shrink Film</div>
    </div>
    <div class="categories_section_block">
        <img src="<?php echo $this->getViewFileUrl('images/storage.png'); ?>" alt="Tool Storage" class="categories_section_block_image">
        <div class="categories_section_block_item">Tool Storage</div>
    </div>
</div>
