<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
/** @var Magento\Customer\Block\Account\Customer $block */
?>
<?php if($block->customerLoggedIn()): ?>
    <div class="customer-welcome"
         data-bind="scope: 'customer'">
        <span class="customer-name"
              role="link"
              tabindex="0">
            <span class="custom-name-account"><?= $block->escapeHtml(__('Account')) ?>:</span>
            <button class="customer-name-btn">
                <!-- ko if: (customer().account_number)-->
                <span>#</span>
                <span class="customer-name-link-number" data-bind="text: customer().account_number"></span>
                <!-- /ko -->
                <span class="customer-name-link-name" data-bind="text: customer().fullname"></span>
            </button>
        </span>
        <!-- ko if: (customer().account_number)-->
        <span class="shipto-name"
              role="link"
              tabindex="0"
              data-bind="scope: 'customer'">
            <span class="custom-name-account"><?= $block->escapeHtml(__('Ship To')) ?>:</span>
            <button class="customer-shipto-btn">
                <span class="shipto-city" data-bind="text: customer().shipto_city"></span>
                <span class="shipto-postcode" data-bind="text: customer().shipto_post"></span>
            </button>
        </span>
        <!-- /ko -->
        <script type="text/x-magento-init">
        {
            "*": {
                "Magento_Ui/js/core/app": {
                    "components": {
                        "customer": {
                            "component": "Magento_Customer/js/view/customer"
                        }
                    }
                }
            }
        }
        </script>
    </div>

    <div id="customer_info__popup" class="modal-container">
        <div id="customer_info_component" data-bind="scope:'customerInfoComponent'">
            <!-- ko template: getTemplate() --><!-- /ko -->
            <script type="text/x-magento-init">
            {
                "#customer_info_component": {
                    "Magento_Ui/js/core/app": {
                       "components": {
                            "customerInfoComponent": {
                                "component": "BlueAcorn_Company/js/customerInfoComponent",
                                "template" : "BlueAcorn_Company/customer-info-component",
                                "buttonSelector" : ".customer-name-btn, .customer-shipto-btn, .change-ship-to",
                                "popupSelector" : "#customer_info__popup",
                                "apiUrl"   : "<?= $block->getUrl('rest/V1/companyData'); ?>"
                            }
                        }
                    }
                }
            }
            </script>
        </div>
    </div>
<?php endif; ?>
