<div class="categories_block">
    <h1 class="categories_block_header"><?= __('Featured Categories'); ?></h1>
    <div class="categories_block_content">
        <img src="{{view url=Bogdan_CmsContent/images/bulk.png}}" alt="Bulk Nails" class="categories_block_content_image">
        <div class="categories_block_content_item"><?= __('Bulk Nails'); ?></div>
    </div>
    <div class="categories_block_content">
        <img src="{{view url=Bogdan_CmsContent/images/collated.png}}" alt="Collated Nails" class="categories_block_content_image">
        <div class="categories_block_content_item"><?= __('Collated Nails'); ?></div>
    </div>
    <div class="categories_block_content">
        <img src="{{view url=Bogdan_CmsContent/images/staplers.png}}" alt="Staplers" class="categories_block_content_image">
        <div class="categories_block_content_item"><?= __('Staplers'); ?></div>
    </div>
    <div class="categories_block_content">
        <img src="{{view url=Bogdan_CmsContent/images/shrink.png}}" alt="Shrink Film" class="categories_block_content_image">
        <div class="categories_block_content_item"><?= __('Shrink Film'); ?></div>
    </div>
    <div class="categories_block_content">
        <img src="{{view url=Bogdan_CmsContent/images/storage.png}}" alt="Tool Storage" class="categories_block_content_image">
        <div class="categories_block_content_item"><?= __('Tool Storage'); ?></div>
    </div>
</div>
