<?php

/** @var \Magento\Framework\View\Element\Template $block */

?>


<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                      "UiComponent": {
                        "component": "Bogdan_Customer/js/logged"
                      }
                }
             }
        }
    }
</script>


<div class="block block-customer-login" data-bind="scope: 'UiComponent'">
    <!-- ko ifnot: isLoggedIn() -->
    <div data-bind='scope: "logged"' class="block-content" aria-labelledby="block-customer-login-heading">
        <form class="form form-login"
              action="<?= $block->escapeUrl($block->getPostActionUrl()) ?>"
              method="post"
              id="login-form"
              data-mage-init='{"validation":{}}'>
            <?= $block->getBlockHtml('formkey') ?>
            <fieldset class="fieldset login" data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>">
                <div class="field email required">
                    <div class="control">
                        <input placeholder="<?= $block->escapeHtml(__('Email Address')) ?>" name="login[username]"
                               value="<?= $block->escapeHtmlAttr($block->getUsername()) ?>" <?php if ($block->
                        isAutocompleteDisabled()) : ?> autocomplete="off"<?php endif; ?>
                               id="email" type="email" class="input-text"
                               title="<?= $block->escapeHtmlAttr(__('Email')) ?>"
                               data-mage-init='{"mage/trim-input":{}}'
                               data-validate="{required:true, 'validate-email':true}">
                    </div>
                </div>
                <div class="field password required">
                    <div class="control">
                        <input placeholder="<?= $block->escapeHtml(__('Password')) ?>" name="login[password]"
                               type="password" <?php if ($block->isAutocompleteDisabled()) : ?>
                            autocomplete="off"<?php endif; ?>
                               class="input-text" id="pass" title="<?= $block->escapeHtmlAttr(__('Password')) ?>"
                               data-validate="{required:true}">
                    </div>
                </div>
                <?= $block->getChildHtml('form_additional_info') ?>
                <div class="actions-toolbar">
                    <div class="primary">
                        <button type="submit" class="action login primary" name="send" id="send2">
                            <span><?= $block->escapeHtml(__('LOG IN')) ?></span></button>
                    </div>
                </div>

                <div class="registartion-link">
                    <a href="#" class="link">Become a Customer</a>
                </div>
            </fieldset>
        </form>
    </div>
    <!-- /ko -->

    <!-- ko if: isLoggedIn() -->
    <div class="block-content header_login_information_wrapper">
        <div class="header_login_block" >
            <a href="#" class="header_login_block_link link_globus">Eng</a>
            <span class="header_login_link_description link_location">
                Your Store:
                <a href="#" class="header_login_block_link">Charleston</a>
            </span>
        </div>
        <div class="header_login_block">
                        <span class="header_login_link_description">
                Account:
                <a href="#" class="header_login_block_link"># 8675309 Seymour Project</a>
            </span>
            <span class="header_login_link_description">
                Ship To::
                <a href="#" class="header_login_block_link">Charleston, 29412</a>
            </span>
        </div>

        <div class="header_login_block">
            <a href="#" class="header_login_block_link link_favorites">Favorites</a>
            <a href="#" class="header_login_block_link link_account">My Account</a>
        </div>
    </div>
    <!-- /ko -->
</div>




